language: python

python:
  - 2.7
  - 3.6

install:
  - pip install . -r requirements.txt

script:
  - python setup.py test          

after_success: 
    - pip install travis-sphinx nbsphinx sphinx_rtd_theme jupyter_client
    - travis-sphinx build -n
    - travis-sphinx deploy
